export function buildWorkflowScaffold(name: string): Record<string, string> {
  return {
    "metadata.json": JSON.stringify(
      {
        name,
        displayName: `TODO: ${name}`,
        description: "TODO: describe this workflow.",
        version: "1.0.0",
        author: "TODO",
        tags: ["TODO"],
        provider: [],
        runtimes: [],
        runners: ["ubuntu-latest"],
        defaultRunner: "ubuntu-latest",
        smart: false,
        requiredSecrets: {},
        triggers: ["pull_request"],
        stacks: ["any"],
      },
      null,
      2,
    ),
    "workflow.yml": [
      `name: ${name}`,
      "",
      "on:",
      "  pull_request:",
      "    branches: [main]",
      "",
      "jobs:",
      "  task:",
      "    runs-on: ubuntu-latest",
      "    steps:",
      "      - uses: actions/checkout@v4",
      "      - name: TODO",
      '        run: echo "TODO: implement workflow steps"',
    ].join("\n"),
    "README.md": [
      `# ${name}`,
      "",
      "TODO: describe what this workflow does.",
      "",
      "## Install",
      "",
      "```bash",
      `npx openci add owner/repo --workflow ${name}`,
      "```",
    ].join("\n"),
  };
}
